version: '3'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - settings
      - callback-router

  settings:
    build: ./settings
    ports:
      - "8081:8081"

  callback-router:
    build: ./callback-router
    ports:
      - "8082:8082"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
